### ISSUE TITLE
Put coordinates in output message

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-svg#10]
When a shape is being clicked, an output message is being send.  The mouse coordinates (of the clicked position) should be added to the output message.

This way the output message could be routed to another node that generates a _**popup context menu**_ at that position (i.e. on top of the drawing).

In which message field should I put those x and y coordinate?
For example:
```
payload: "mycircle",
topic: "clicked",
screen_location: {x : 50, y : 60}
```
Or perhaps better:
```
payload: {
   "elementId": mycircle",
   "positionX": 50,
   "positionY": 60,
}
topic: "clicked"
```

**Comment by Steve-Mcl** [comment]
Bart, as you are aware this is now implemented however, I suspect the coordinates generated are not correct.

I have used the `msg.coordinates` to show our `contextmenu` node however placement is not as expected.

Will feedback when I know more

**Comment by Steve-Mcl** [comment]
Sorted in jquery branch & handed off nicely to contextmenu :)


![2019-08-27_13-17-24](https://user-images.githubusercontent.com/44235289/63770435-13599680-c8cd-11e9-8fcc-9e584f5d5287.gif)
