### ISSUE TITLE
Not really an issue - but best way to implement

### ISSUE THREAD

**Issue by dbertie1** [bartbutenaers/node-red-contrib-ui-svg#101]
Great node, and I've managed to get floorplans imported and working with lights etc.

I've set up the downstairs and upstairs as different SVG graphics nodes, and these "live" alongside other pages (using other parts of dashboard) for different items (e.g. network quality etc).

The one issue I have is that the properties for the SVG objects are reset each time I reopen (say) downstairs.  So I lose all of the data that was in there and have to wait for them to be repopulated as MQQT messages arrive etc.

Is there a good way to 'retain' data, or have it flowing in to be drawn on for when the node is SVG graphics node is then selected?

Hopefully this makes sense as a question, and I'm sure there must be a straightforward way.

Many thanks,
David

**Comment by bartbutenaers** [comment]
Hi @dbertie1,
You might have a look at another [discussion](https://github.com/bartbutenaers/node-red-contrib-ui-svg/issues/92#issuecomment-805594271) to get some ideas about this. 
Bart

**Comment by dbertie1** [comment]
Super and thanks - I'll have a read.  I was sure I couldn't be the first.

Thanks again, David

**Comment by bartbutenaers** [comment]
David,
If you find anything useful, it would be nice if you could share some ideas.  Perhaps we can add an example page on the [wiki](https://github.com/bartbutenaers/node-red-contrib-ui-svg/wiki)...
Thanks!
Bart

**Comment by dbertie1** [comment]
Super, and will do - I'm just looking at the flow you created using flow memory, very cunning and opened my eyes to a completely new concept!  Now need time to digest ....
