### ISSUE TITLE
Right click menu bug

### ISSUE THREAD

**Issue by andreypopov** [bartbutenaers/node-red-contrib-ui-svg#103]
![2021-11-22_16-06-09](https://user-images.githubusercontent.com/1624839/142867394-a7212c95-33fd-4b8f-bae6-fa8c0cf208bc.png)

please, check

https://github.com/bartbutenaers/node-red-contrib-ui-contextmenu/issues/29

**Comment by bartbutenaers** [comment]
@andreypopov,
Can you install the version from Github and let me know whether it is fixed?
I have tested your example [flow](https://github.com/bartbutenaers/node-red-contrib-ui-svg/pull/93) and my (dbl)click test [flow](https://github.com/bartbutenaers/node-red-contrib-ui-svg/issues/97#issuecomment-969374604), and to me its seems that all works now.

**Comment by bartbutenaers** [comment]
??
