### ISSUE TITLE
Question:  can I add a shape to a drawing programmatically? 

### ISSUE THREAD

**Issue by goofy2k** [bartbutenaers/node-red-contrib-ui-svg#111]
Hi Bart,  nice work !

I consider to start using this to create a simple GUI. I did a quick scan of your help pages but did not (yet) find an answer to my question:

Is it possible to add a shape to an existing drawing, triggered by an incoming message?  For example can I add a data point (a colored cirlcle) with the color and position specified in the incoming message? Or should shapes always be already present ("hard-coded") in the drawing?

**Comment by Steve-Mcl** [comment]
Hi @goofy2k it is right there in the readme...

https://github.com/bartbutenaers/node-red-contrib-ui-svg#supported-commands

**Comment by goofy2k** [comment]
Thanks Steve,   I'm going to give this a try!
