### ISSUE TITLE
Setup node not working correctly

### ISSUE THREAD

**Issue by PekkaHaapanen** [bartbutenaers/node-red-contrib-ui-svg#131]
I wonder why my configuration page for Node-red-contrib-ui-svg looks like this? The tabs are missing (part of their content can be found from the botton of the dialog) I have version 2.3.3, Node-red is v3.1.3 running on a Raspberry Pi
![image](https://github.com/bartbutenaers/node-red-contrib-ui-svg/assets/167639211/3ebfe0e5-200b-4523-a09c-b67802f671f6)

**Comment by bartbutenaers** [comment]
@PekkaHaapanen,
I think you have not installed the Node-RED dashboard?  I mean [this ](https://flows.nodered.org/node/node-red-dashboard)one.  Or not restarted Node-RED after installing it.

**Comment by PekkaHaapanen** [comment]
_I think you have not installed the Node-RED dashboard?_
Yes, that's it. :)
Thanks a million.

**Comment by bartbutenaers** [comment]
You are welcome!
