### ISSUE TITLE
Layout of animations table

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-svg#14]
Currently the screen for the animations is rather full:

![animations](https://user-images.githubusercontent.com/14224149/63208319-ea6a2200-c0d2-11e9-953b-59f9096027e1.png)

But if I put all fields below each other, I think it becomes too long.
But I need to rearrange them, because a single row is too short.  Moreover extra fields might be added in the future, for other SMIL animation types.  E.g. to have the shape following a path ...

**Comment by Steve-Mcl** [comment]
How about a collapsible form that minimises to a description? Then the form layout can be as tall as need be.

**Comment by bartbutenaers** [comment]
Hi Steve,
Could you please draw a quick sketch, to explain how you should do it!
Really appreciate your feedback!!
