### ISSUE TITLE
Handle empty or non-valid SVG

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-svg#15]
When no valid svg element can be found, we will have a null-reference:
```
$scope.svg = $scope.rootDiv.querySelector("svg");
```
Handle this properly

**Comment by Steve-Mcl** [comment]
My thoughts...
1. Default it to `<svg />`
Or
2. Ignore it / do nothing. 
Or
3. Create a Node configuration error if SVG is empty or doesn't have svg root element?

**Comment by bartbutenaers** [comment]
@Steve-Mcl ,
Or perhaps display an svg containing a **text**-element “_no drawing has been specified_” …

**Comment by Steve-Mcl** [comment]
> Or perhaps display an svg containing a text-element “no drawing has been specified” ...

Yeah, thats seems reasonable

![image](https://user-images.githubusercontent.com/44235289/63942451-b1806480-ca65-11e9-94e2-7a632c73c359.png)


```
<svg width="200" height="50" xmlns="http://www.w3.org/2000/svg"> 
 <g>
  <rect stroke="#000000" id="svg_2" height="50" width="200" y="2.73322" x="2.00563" stroke-width="5" fill="#ff0000"/>
  <text font-weight="bold" stroke="#000000" xml:space="preserve" text-anchor="middle" font-family="Sans-serif" font-size="24" id="svg_1" y="35.85669" x="100" stroke-width="0" fill="#000000">SVG is empty</text>
 </g>
</svg>
```

**Comment by bartbutenaers** [comment]
Implemented
