### ISSUE TITLE
Extra animation triggers

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-svg#19]
Steve asked [here](https://discourse.nodered.org/t/announce-node-red-contrib-ui-svg-feedback-request/14431/16?u=bartbutenaers) to intercept extra pointer events, to trigger animations.

**Comment by Steve-Mcl** [comment]
Is this now feature complete?

**Comment by bartbutenaers** [comment]
Yes think so
