### ISSUE TITLE
Extra clickable events

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-svg#21]
Currently only the left-mouse-click event is supported.  Steve asked to support extra events, so perhaps we can _**add an 'Event' column containing a dropdown**_:
+ **Left mouse**: already supported
+ **Right mouse**: perhaps we can use the '_contextmenu_' event like in this [StackOverflow](https://stackoverflow.com/questions/6605978/right-mouse-click-detection-on-svg-shape-in-javascript-not-working) discussion.
+ **Double click**: The SVG standard does **not** define a double click event ([dblclick](https://www.w3schools.com/jsref/event_ondblclick.asp), and Firefox provide [no support](https://bugzilla.mozilla.org/show_bug.cgi?id=360145) for double clicks in SVGs.  Although the third-party [svg.js](https://github.com/svgdotjs/svg.js/blob/4ffb59abe80ff6815866a37447db62933b064813/src/modules/optional/sugar.js#L161) library seems to be able to support it, so perhaps nowadays it works ...  Otherwise we can perhaps combine somehow click events when two click events happen within a small time interval (so in that case we have a double click event) ...

**Comment by Steve-Mcl** [comment]
We can at minimum support modifier keys. They appear in the `evt` 

May need to consider touch events too.

**Comment by bartbutenaers** [comment]
Hey Steve, I hadn't seen your "May need to consider touch events too" comment ...
