### ISSUE TITLE
Adjustable viewport

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-svg#22]
Not an urgent one, but perhaps in the future we could make the viewport adjustable via the input messages.  That way users can add zoom/pan buttons to their dashboard, and let us know whether we should zoom in/out ...

**Comment by Steve-Mcl** [comment]
Will need to check but I suspect we can do this via update_attribute

**Comment by bartbutenaers** [comment]
The wiki has now a [tutorial ](https://github.com/bartbutenaers/node-red-contrib-ui-svg/wiki/Manipulate-the-viewbox) about how to accomplish this.
