### ISSUE TITLE
Include example flows in the Node-RED flow editor menu

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-svg#24]
Not urgent, but would be nice to include some examples in the Node-RED flow editor menu.

Just like I did for my heatmap node:
![image](https://user-images.githubusercontent.com/14224149/63550719-8d87c500-c533-11e9-801a-f6456b3702c7.png)

To implement this we only need to put some example _**flow json files in our Github project under an 'examples' folder**_.  Similar to the heatmap node:
https://github.com/bartbutenaers/node-red-contrib-ui-heatmap/tree/master/examples

**[EDIT 23/08]** We should do this just before we reach the final project status, to avoid us having to update the example flows over and over again ...

**Comment by Steve-Mcl** [comment]
Source for SVG components

http://groov.com/svg-library/

**Comment by bartbutenaers** [comment]
Hi @Steve-Mcl ,
Are you sure this isn't a proposal for another issue?  Perhaps about sharing reusable widgets?

**Comment by bartbutenaers** [comment]
Done already
