### ISSUE TITLE
Test operations in other browsers

### ISSUE THREAD

**Issue by Steve-Mcl** [bartbutenaers/node-red-contrib-ui-svg#29]
So far, all my development has been Chrome.

I realise IE will be problematic - should we care?  
* There are several workarounds for IE not scaling correctly.  
* Ive seen instances where events dont work - that could be a problem.

**Comment by bartbutenaers** [comment]
@Steve-Mcl ,
I also tested everything on Chrome only.
We can of course do some basic testing on a couple of browsers.  And we can ask – as soon as we publish the beta – if users want to test it on other browsers …

And add to the readme file that we have used Chrome during development …

**Comment by bartbutenaers** [comment]
This node is already being used by lots of users.  If something would be wrong on some browsers, I assume we would already have gotten feedback a long time ago.  So will close this one ...
