### ISSUE TITLE
Code beautifier

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-svg#30]
As discussed with @Steve-Mcl we will introduce a code beautifier, for example this [one](https://github.com/beautify-web/js-beautify/blob/510cf7a9a82cb7f7515ac6988554086d0e5a7bc8/test/data/html/tests.js#L2375).
+ Add it as a dependency to the package.json
+ Add a button below the SVG text input field
+ Automatically call it before the SVG text input field is being filled (e.g. when the third party editor content is being imported into the svg input field).

**Comment by Steve-Mcl** [comment]
Bart, the last point, I didn't do. 
 My take on that was a user may not want or like the format generated by the prettyfier. 

If you agree we can close this?

**Comment by Steve-Mcl** [comment]
Sorry, I misunderstood, the automatic option is for formatting AFTER popup editor. 

I should be able to do that but my concern is if the formatter gets it wrong, it prevents us getting useful SVG out of the editor. Thoughts?

**Comment by bartbutenaers** [comment]
@Steve-Mcl ,
Perhaps you can add a checkbox "_beautify code from svg editor_" on our "_Settings_" tabsheet?

**Comment by Steve-Mcl** [comment]
Done, now in DEV branch
