### ISSUE TITLE
Only show 'Save' popup if changes available

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-svg#31]
When leaving the DrawSvg iFrame, a popup is displayed:

![image](https://user-images.githubusercontent.com/14224149/65080560-e7987080-d9a1-11e9-8244-27a6ca270fb6.png)

This popup is only required when the SVG source has been changed.

**Comment by bartbutenaers** [comment]
Seems DrawSvg has internally already an isDirty flag.  Joseph will make this public available via the API in a future version...

**Comment by Steve-Mcl** [comment]
Any word on this Bart?

**Comment by Steve-Mcl** [comment]
Fixed in master branch
