### ISSUE TITLE
Fontawesome font in DrawSvg

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-svg#34]
Currently DrawSvg doesn't support the FontAwesome font, so we have asked Joseph Liard if he can consider adding this in a next version.  To be continued ...

**Comment by Steve-Mcl** [comment]
Can we consider this closed?

**Comment by bartbutenaers** [comment]
Yep, since Joseph has added FontAwesome support both in his cloud service and our local DrawSvg zip file.
