### ISSUE TITLE
Wrong notification when invalid SVG

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-svg#36]
@Steve-Mcl reported:

If SVG is invalid, the editor loads and states SVG is invalid - however, upon closing, the popup save dialog shows "Error loading SVG!"...

![image](https://user-images.githubusercontent.com/14224149/65822565-b4c66600-e246-11e9-8c0b-8a8114206dae.png)

**Comment by Steve-Mcl** [comment]
fixed in branch popupfix (close issue after merging into master)

**Comment by Steve-Mcl** [comment]
Fixed in master
