### ISSUE TITLE
Save button white

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-svg#37]
@Steve-Mcl reported: On my laptop, I'm running NR V1.beta3 - the Save Button on the DrawSVG no longer has a save icon (fa fa-save is present in devtools).

![image](https://user-images.githubusercontent.com/14224149/65822575-f8b96b00-e246-11e9-8263-aed490bd58d4.png)

**Comment by Steve-Mcl** [comment]
Fixed in branch popupfix ...

![image](https://user-images.githubusercontent.com/44235289/66705713-26f87980-ed22-11e9-9421-3670b966d2f3.png)

**Comment by Steve-Mcl** [comment]
close issue after merging into master
