### ISSUE TITLE
SVG beautifier not entire correct

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-svg#41]
After beautifiying a raw SVG string, the closing ```</svg>``` is not added on a new line:
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" x="0" y="0" viewBox="0 0 900 710" width="100%" height="100%">
  <circle id="mycircle" cx="182.901" cy="91.4841" style="fill:rosybrown;stroke:black;stroke-width:1px;" r="48" /></svg>
```

**Comment by Steve-Mcl** [comment]
Works for me.
![2019-10-13_14-38-33](https://user-images.githubusercontent.com/44235289/66716582-3e3d7280-edc7-11e9-8ee5-644e401e969f.gif)


update... ah shoot, its a problem with self closing tags.

Raised and issue on repo...
https://github.com/beautify-web/js-beautify/issues/1718

**Comment by bartbutenaers** [comment]
288 open issues on that library...

**Comment by Steve-Mcl** [comment]
Not sure if you noticed but https://github.com/beautify-web/js-beautify/issues/1718 is now closed Bart.  It doesnt say if the problem was actually fixed mind!

**Comment by Steve-Mcl** [comment]
Just checked & it is fixed :)

**Comment by bartbutenaers** [comment]
Hey Steve (@Steve-Mcl ),
I had checked it some time ago, but then it was still open.
Indeed it seems to be working now, if I reinstall the svg node.
Thanks for the update!
Bart
