### ISSUE TITLE
Integration with SVG-Edit

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-svg#5]
Currently there is no SVG drawing editor integrated with this node.  It looks to me that SVG-EDit online [editor](https://svg-edit.github.io/svgedit/releases/svg-edit-2.8.1/svg-editor.html) can be integrated with this node (via their [embedapi](https://github.com/timkelty/svg-editor-craft/blob/master/svgeditor/resources/editors/svg-edit/embedapi.html): I could send our SVG string and let them render it as a drawing, and - as soon as the changes are made in SVG-edit - the updated SVG string would be stored automatically in our node.

+ I'm not sure if this would be useful?
+ The memory footprint of this node would grow, since the SVG-Edit libraries need to be included in this node.

**Comment by Steve-Mcl** [comment]
Bart, found [this](https://github.com/Harvie/DokuWiki-Plugin-SVGEdit/blob/master/script.js)

It may shortcut development time for embedding SVG editor

**Comment by bartbutenaers** [comment]
Indeed a good code snippet to get started!!

**Comment by bartbutenaers** [comment]
@Quagmireman,
Some feedback on your proposal:
+ I had chosen SVG-edit, because it is a web application & it can be run locally & it has an API that allows it to be embedded?  
+ I know that Inkscape is popular, but I thought it was not a web application?  
+ The Method-Draw editor that you mention, seems to be not maintained anymore on [Github](https://github.com/methodofaction/Method-Draw).  Moreover I see that it is a fork of SVG-Edit, so then we are back at our original proposal.

But if we ever find another web-based SVG editor with a simple API, we can always add it as an extra integration for our node...
Bart

**Comment by bartbutenaers** [comment]
We have integrated DrawSvg instead.
