### ISSUE TITLE
get attributeValue of an attributeName

### ISSUE THREAD

**Issue by d0d04m3** [bartbutenaers/node-red-contrib-ui-svg#54]
hi 
I need this feature to get attributeValue of an attributeName SVG element?
check this post
https://discourse.nodered.org/t/ui-svg-attributevalue-of-an-attributename/24445

**Comment by bartbutenaers** [comment]
Hi,
I'm closing this issue since this has already been asked by someone else lasts week:
https://github.com/bartbutenaers/node-red-contrib-ui-svg/issues/51#issuecomment-609080312
