### ISSUE TITLE
Animation fill="freeze" not working if configured via Animations tab

### ISSUE THREAD

**Issue by ipamaas** [bartbutenaers/node-red-contrib-ui-svg#60]
The animation fill="freeze" is not working if set in Animations tab.
The animation will jump back to the from-Values (resets the animation).
Tested with current versions of Opera and Firefox.
Not working::
![grafik](https://user-images.githubusercontent.com/41891231/81271833-e9a46200-904c-11ea-8fb1-7dd9fca587ce.png)
Working if directly embedded in SVG file:
```sh
    <animate 
       xlink:href="#svg_press_element"
       attributeName="points"
       from="107.829,108.999 107.265,178.435 90.3291,178.999 90.3291,197.628 160.894,197.063 160.33,178.998 142.265,178.434 141.136,108.998"
       to="107.829,139.483 107.265,208.919 90.3291,209.483 90.3291,228.112 160.894,227.547 160.33,209.482 142.265,208.918 141.136,139.482" 
       dur="6s"
       fill="freeze"
       id="press_down_anim"/>
```

**Comment by bartbutenaers** [comment]
Hi Matthias,
could you please create export a (simplified) flow so I can reproduce this quickly.  Because I'm rather short on free time at the moment...
Thanks!!!
Bart

**Comment by ipamaas** [comment]
Hi Bart,
please find attached a simplified woking and a failing sample flow.

[flow_samples.zip](https://github.com/bartbutenaers/node-red-contrib-ui-svg/files/4592630/flow_samples.zip)

There's no rush to solve this now as the workaround of embedding the animation in the svg itself is still working.

BR Matthias

**Comment by bartbutenaers** [comment]
Hey Matthias,
Sorry for the delay.
I have fixed this in the *"panzoom"* branch on Github, which will become soon the 2.0.0 release of this node.
Now it seems to be working fine:

![svg_end_freeze_fix](https://user-images.githubusercontent.com/14224149/86541027-d0634900-bf09-11ea-9198-8e824f81f706.gif)

Kind regards,
Bart
