### ISSUE TITLE
Refresh required when incorrect url

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-svg#62]
When the dashboard is being used over https but the drawsvg url is http (in Settings tab) then then iframe stays empty.  And a browser refresh is required to get back to the flow editor :-(

Changing the Drawsvg from http to https is a workaround ...

See for example this [discussion](https://www.zabbix.com/forum/zabbix-cookbook/27037-automatic-graph-of-all-lld-items-per-host?p=189542#post189542).

**Comment by boisei0** [comment]
Bart, can the URL field be populated dynamically? Like checking if the browser viewing the form is connecting over http or https and creating and filling the URL based on that.

**Comment by bartbutenaers** [comment]
Hey Lena,
Thanks for your feedback! 

![image](https://user-images.githubusercontent.com/14224149/81896230-6d61cf80-95b4-11ea-9a5d-f199c6f4f7bc.png)

The user needs to enter the url of the cloud service, or the url of the local service (if [node-red-contrib-drawsvg](https://github.com/bartbutenaers/node-red-contrib-drawsvg) is being used).   The refresh button - after the url input fields - updates the field with the default (http) url.

But there are some issues with CORS unfortunately.  I have described those issues at the time being on the [readme ](https://github.com/bartbutenaers/node-red-contrib-drawsvg#use-cases) page.  Therefore I have no general solution yet.  If you have any ideas or suggestions, don't hesitate to let me know!

BTW. Whatever reason the URL cannot be reached, it should at least show an alert popup and return to the Node-RED editor (instead of freezing).  But need to dig into this whenever I find time, because @Steve-Mcl was the jschannel expert of this node ;-)

Bart

**Comment by boisei0** [comment]
The gears have started spinning in my head. I’ve a couple (vague) ideas that could work, but I’ll let you know when I’ve more clarity.

**Comment by bartbutenaers** [comment]
Solved.  See other [issue](https://github.com/bartbutenaers/node-red-contrib-ui-svg/issues/64#issuecomment-649857504).
