### ISSUE TITLE
Doesn't work on https pages

### ISSUE THREAD

**Issue by arybitskiy** [bartbutenaers/node-red-contrib-ui-svg#64]
Hi,

I have node-red on a https connection and it doesn't work because editor url is `http://drawsvg.org/drawsvg.html`.
If you would change this line
https://github.com/bartbutenaers/node-red-contrib-ui-svg/blob/33ca6da11021086af6142f8b1b4c3e4bf8b26e7a/svg_graphics.html#L336
to
```
editorUrl: {value: "//drawsvg.org/drawsvg.html"},
```
That should fix issue.

**Comment by bartbutenaers** [comment]
Hello @arybitskiy,
This issue was already quite some time on my todo list.
Very kind of you to share the solution!
I will update it in the #panzoom branch which is the version 2.0.0 branch.
Thanks a lot!!
Bart

**Comment by bartbutenaers** [comment]
P.S. I have also added a fix to the panzoom branch, to give a (timeout) error after 2 seconds when the popup window cannot be closed (due to invalid editor url):

![image](https://user-images.githubusercontent.com/14224149/85803511-9941aa80-b747-11ea-8671-8884e933a061.png)
