### ISSUE TITLE
event not working after upgrade

### ISSUE THREAD

**Issue by smcgann99** [bartbutenaers/node-red-contrib-ui-svg#77]
Hi,

I have a floor plan with icons for devices. Clicking sends a message to toggle the device on or off. This WAS working before upgrade. Reading the notes I see that there are some changes to payload format, but as I'm just using the built in event feature, so not sure why this would affect me? The events no longer trigger when clicked.

I have checked debug from node and noticed that the payload doesn't seem to match the documentation. there is no "elementId" or "selector" , this is what I see -

msg : Object
object
type: "click"
pageX: 1146
pageY: 425
screenX: 1146
screenY: 527
clientX: 1146
clientY: 425
svgX: 356
svgY: 304
bbox: array[4]

**Comment by RavenSpy** [comment]
Hi,
I see that I am not the only one who is having the same problem, I thought it was just me.
The same thing happens to me, I have tried to do a zero installation and easy circle click event, but it only gives the same results.
![output_info](https://user-images.githubusercontent.com/12830687/100520463-14e3cf80-319e-11eb-828b-c836a1ce8131.png)

**Comment by bartbutenaers** [comment]
Hello @smcgann99,
In the 2.0.0 version there were indeed breaking changes.  Unfortunately I could not avoid that.  Therefore it was a released as a major vetsion.

**Comment by RavenSpy** [comment]
I made a clean installation, with last versión of node-red-dashboard 2.24.1 and node-red-contrib-ui-svg 2.1.0.
![event](https://user-images.githubusercontent.com/12830687/100520718-9ab44a80-319f-11eb-8db9-2b0196e9152d.PNG)
![simple](https://user-images.githubusercontent.com/12830687/100520719-9b4ce100-319f-11eb-88fb-882ab89bb1b3.PNG)

**Comment by bartbutenaers** [comment]
Hi @RavenSpy,
I will have a look this evening, and try to create a fix in a couple of hours.  First some family business...
Bart

**Comment by RavenSpy** [comment]
Of course Bart, don't worry, it's not a matter of life and death. Enjoy the family!
Thanks in advice, regards.

**Comment by smcgann99** [comment]
Bart, I think it was latest before 2.1.

**Comment by bartbutenaers** [comment]
Hey guys,
Luckely the wife and kids had to do some other things before our movie evening started :-)
So I quickly fixed it and published version ***2.1.1*** on NPM.  It is now available in the palette:

![image](https://user-images.githubusercontent.com/14224149/100521451-f680d280-31a3-11eb-9cc6-b573b2788395.png)

Would be nice if you could let me know if it is solved now.
Because I can imagine this is a nasty bug for users...

**Comment by RavenSpy** [comment]
Lol Bart so fast jaja.
It seems working for me.
![worked](https://user-images.githubusercontent.com/12830687/100522260-b7ee1680-31a9-11eb-8971-cfb39ed97cd0.png)
Thanks a lot!

**Comment by smcgann99** [comment]
All good for me as well thanks very much. 
If I can just figure out why my animations work in firefox but not chrome - but thats for another day ;-)
