### ISSUE TITLE
Debug ui-svg

### ISSUE THREAD

**Issue by tkirchm** [bartbutenaers/node-red-contrib-ui-svg#87]
Hi @bartbutenaers,

you wrote some pretty cool instruction how to debug node-red in Chrome but I can't find out how to debug ui-svg.

Chrome:
I follow your [instruction](https://discourse.nodered.org/t/how-to-debug-an-own-node-with-the-node-js-debugger/5737/4?u=bartbutenaers) and start my node-red on a raspberry pi with 
node --inspect=0.0.0.0:5858 /usr/lib/node_modules/node-red/red.js
![image](https://user-images.githubusercontent.com/58719851/104021850-c7f11100-51bf-11eb-9865-d5ef8865ac03.png)
and my chrome://inspect finds it
![image](https://user-images.githubusercontent.com/58719851/104021969-ed7e1a80-51bf-11eb-8a07-c057c1e705d2.png)
When I pause script execution it stops and shows me some script but it will never stop at debugger; or a Breakpoint in svg_graphics.js.
The file location in Sources is file:///home/pi/.node-red/node_modules/node-red-contrib-ui-svg/svg_graphics.js
![debug](https://user-images.githubusercontent.com/58719851/104024306-384d6180-51c3-11eb-95b0-e504d611c482.gif)

What am I missing?

Thomas

**Comment by bartbutenaers** [comment]
Hi Thomas,

That tutorial is about debugging the _**server-side**_ of a node.  For example when you want to debug what happens in your Node-RED flow, when a message enters the node.  The server-side Javascript code is executed by the NodeJS application server (which you have started via your `node ....` command.

However for UI nodes (like the SVG UI node), most of the stuff happens not in the server but in the frontend.  The _**frontend-side**_ Javascript code will be executed by the browser that is running your dashboard.  So what you need to do:

1. Put a `debugger;` statement somewhere in the frontend Javascript code (svg_graphics.js file), in some code snippet that you want to see what is going on ...
2. Then open the Chrome developer tools on the Chrome tabsheet where your dashboard is running.  As soon as Chrome arrives at your debugger statement, the debugger wilt pause there and you can start debugging.

This is indeed very confusing.  The svg_graphics.js file contains both the server-side code (on top) and the dashboard code (starting from initController if I'm not mistaking).  

Good luck with it!
Bart

**Comment by tkirchm** [comment]
Tanks a lot.
As always super fast and precise.
