### ISSUE TITLE
Error: "None of the specified bindings fields ..."

### ISSUE THREAD

**Issue by IoTPlay** [bartbutenaers/node-red-contrib-ui-svg#88]
I stream in info from a solar system to an SVG panel - and every so often I get this message - it looks like this is a field sent to SVG which does not exist in the SVG fields defined. Error message below.
`
"None of the specified bindings fields (in the config screen or data-bind-text or data-bind-values) are available in this message."
`

Am I on the right track?

**Comment by bartbutenaers** [comment]
Hi Jéan,
I think you send - at those moments - a message with `msg.topic == "databind"`, but none of binding fields (specified in the *"Bindings"* tabsheet) is available in that message.  If you send a message with that topic, the node assumes you want to use data binding, so at least one of the data binding fields (from the *"Bindings"* tabsheet) should be available in that message.

Does that make sense in your case?  Can you verify:
+ Do you have lines specified in your *"Bindings"* tabsheet?
+ Do you send messages with topic "databind"?

If your setup is ok, then perhaps you found a bug ...
Bart

**Comment by IoTPlay** [comment]
Sorted out, it happens when I send a payload which does not exist in the svg def. A bit difficult to fault find - but found it, thank you

**Comment by IoTPlay** [comment]
#closed
