### ISSUE TITLE
RFE: indefinite checkbox for repeatCount

### ISSUE THREAD

**Issue by hobbes1069** [bartbutenaers/node-red-contrib-ui-svg#94]
SVG allows for the repeatCount to be "indefinite", in the context of NodeRED, I would think a checkbox that greys out the numerical box would be the best way to handle it.

I've got a "Fan" SVG that I'm animating when the temperature goes over a certain value and I'd like it to stay running until the temperature drops below the set point. I could use a crazy high value but the spec allows for "indefinite".

**Comment by bartbutenaers** [comment]
Hi Richard (@hobbes1069),

That indeed makes sense.
Unfortunately I'm not developing at the moment, due to a surgery.  So you will have to wait a bit ...
But I have added it to my (growing) todo list!

Kind regards,
Bart

**Comment by hobbes1069** [comment]
Well I'm not enough of a JS programmer to do it myself but I might try to get some pointers from the forums. If successful I'll submit a PR.

**Comment by Steve-Mcl** [comment]
Hi. 

Can I suggest instead of an extra checkbox, if 0 is an invalid value for the animation count that we simply allow 0 & interpret it as infinity? 

UI mods are a pain.

**Comment by hobbes1069** [comment]
Actually it looks like that's already the case:
```
if (smilAnimation.repeatCount === "0") {
          animationElement.setAttribute("repeatCount"  , "indefinite");
}
```

It's just not in the documentation AFAIKT. Admittedly the documentation is quite long compared to other node types.

**Comment by Steve-Mcl** [comment]
I thought it was. I might have even written that line 😂

**Comment by bartbutenaers** [comment]
> It's just not in the documentation AFAIKT.

Thanks guys for sorting this out!
I will add it to the readme later on...

> Admittedly the documentation is quite long compared to other node types.

And on your request it now will get longer again :-)

**Comment by bartbutenaers** [comment]
Seems it was already mentioned in the documentation, so I didn't need to add anything ...

![image](https://user-images.githubusercontent.com/14224149/121429935-c21e7800-c977-11eb-813c-804b8f2ed7a1.png)
